import type { Metadata } from "next";
import { EnumLocale } from "../enums";
import { getLocale } from "./locales";
import LocaleProvider from "../providers/LocaleProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Params {
  locale: EnumLocale;
}

interface Props {
  children: React.ReactNode;
  params: Promise<Params>;
}

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;
  const translate = await getLocale(locale);

  return (
    <html lang={locale}>
      <body>
        <LocaleProvider t={translate} locale={locale}>
          {children}
        </LocaleProvider>
      </body>
    </html>
  );
}
